version: '3.8'
services:
    alexnet:
        build:
            context: .
            dockerfile: Dockerfile.alexnet
        ports:
            - "8888:8888"
            - "8097:8097"
        volumes:
            - type: bind
              source: ${PWD}
              target: /tmp/workspace
        working_dir: /tmp/workspace
        command: jupyter notebook --port=8888 --no-browser --ip=0.0.0.0 --allow-root --NotebookApp.token='' --NotebookApp.password=''